#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-proj-soname13
Version  : 5.2.0
Release  : 3
URL      : http://download.osgeo.org/proj/proj-5.2.0.tar.gz
Source0  : http://download.osgeo.org/proj/proj-5.2.0.tar.gz
Summary  : Cartographic Projections Library.
Group    : Development/Tools
License  : MIT
Requires: compat-proj-soname13-lib = %{version}-%{release}
Requires: compat-proj-soname13-license = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-cmake
BuildRequires : buildreq-mvn
# Suppress generation of debuginfo
%global debug_package %{nil}

%description
# PROJ
PROJ is a generic coordinate transformation software, that transforms
coordinates from one coordinate reference system (CRS) to another.
This includes cartographic projections as well as geodetic transformations.

%package lib
Summary: lib components for the compat-proj-soname13 package.
Group: Libraries
Requires: compat-proj-soname13-license = %{version}-%{release}

%description lib
lib components for the compat-proj-soname13 package.


%package license
Summary: license components for the compat-proj-soname13 package.
Group: Default

%description license
license components for the compat-proj-soname13 package.


%prep
%setup -q -n proj-5.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1567833911
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1567833911
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-proj-soname13
cp COPYING %{buildroot}/usr/share/package-licenses/compat-proj-soname13/COPYING
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/cct
rm -f %{buildroot}/usr/bin/cs2cs
rm -f %{buildroot}/usr/bin/geod
rm -f %{buildroot}/usr/bin/gie
rm -f %{buildroot}/usr/bin/invgeod
rm -f %{buildroot}/usr/bin/invproj
rm -f %{buildroot}/usr/bin/nad2bin
rm -f %{buildroot}/usr/bin/proj
rm -f %{buildroot}/usr/include/geodesic.h
rm -f %{buildroot}/usr/include/org_proj4_PJ.h
rm -f %{buildroot}/usr/include/proj.h
rm -f %{buildroot}/usr/include/proj_api.h
rm -f %{buildroot}/usr/include/projects.h
rm -f %{buildroot}/usr/lib64/libproj.so
rm -f %{buildroot}/usr/lib64/pkgconfig/proj.pc
rm -f %{buildroot}/usr/share/man/man1/cct.1
rm -f %{buildroot}/usr/share/man/man1/cs2cs.1
rm -f %{buildroot}/usr/share/man/man1/geod.1
rm -f %{buildroot}/usr/share/man/man1/gie.1
rm -f %{buildroot}/usr/share/man/man1/proj.1
rm -f %{buildroot}/usr/share/man/man3/geodesic.3
rm -f %{buildroot}/usr/share/man/man3/pj_init.3
rm -f %{buildroot}/usr/share/proj/CH
rm -f %{buildroot}/usr/share/proj/GL27
rm -f %{buildroot}/usr/share/proj/IGNF
rm -f %{buildroot}/usr/share/proj/ITRF2000
rm -f %{buildroot}/usr/share/proj/ITRF2008
rm -f %{buildroot}/usr/share/proj/ITRF2014
rm -f %{buildroot}/usr/share/proj/epsg
rm -f %{buildroot}/usr/share/proj/esri
rm -f %{buildroot}/usr/share/proj/esri.extra
rm -f %{buildroot}/usr/share/proj/nad.lst
rm -f %{buildroot}/usr/share/proj/nad27
rm -f %{buildroot}/usr/share/proj/nad83
rm -f %{buildroot}/usr/share/proj/null
rm -f %{buildroot}/usr/share/proj/other.extra
rm -f %{buildroot}/usr/share/proj/proj_def.dat
rm -f %{buildroot}/usr/share/proj/world

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libproj.so.13
/usr/lib64/libproj.so.13.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-proj-soname13/COPYING
